spring:
  application:
    name: bank-poc-inactivity-kstream
  kafka:
    bootstrap-servers:
      - localhost:9092
  cloud:
    function:
      definition: heartbeatBinder;transactionMonitoring
    stream:
      kafka:
        streams:
          binder:
            application-id: processor12
            configuration:
              '[spring.json.trusted.packages]': '*'
              default.value.serde: com.abcbank.userinactivity.bankpocinactivitykstream.serdes.CustomSerdes$CustomerSerde                
            deserialization-exception-handler: logAndContinue
  
          bindings:
            transactionMonitoring-out-0:
              producer:
                keySerde: 
  
           
      bindings:
        heartbeatBinder-in-0.destination: heartbeat
        transactionMonitoring-in-0.destination: transactions
        transactionMonitoring-out-0.destination: triggers

  datasource:
    url: jdbc:mysql://localhost:3306/bank_poc
    username: prem
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: bindings, beans, health, info       

user:
  heartbeat:
    monitoring:
      interval: 30000
      timeDifference: 20000
      
  tables:
    refresh:
      interval: 5000
      
      
customerMicroserviceUrl: "http://localhost:8080"